baseURL = 'https://blog.aayushg.com/'
languageCode = 'en-us'
title = "aayush's thoughts"
theme = "hackerman"
googleAnalytics = 'G-K3VZM7ZJ7M'
enableGitInfo = true
description = "Aayush's blog. Discusses zk cryptography including plume, zk email, quantum, and vickrey auctions on chain. Also reviews and recs for hidden gem movies, TV shows, and travel recs."
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
[params]
    description = "Aayush's blog. Discusses zk cryptography including plume, zk email, quantum, and vickrey auctions on chain. Also reviews and recs for hidden gem movies, TV shows, and travel recs."
[markup.goldmark.renderer]
    hardWraps = true
