baseURL = 'https://blog.aayushg.com/'
languageCode = 'en-us'
title = "aayush's thoughts"
theme = "hackerman"
description = "blog"
googleAnalytics = 'G-K3VZM7ZJ7M'
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
